apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  selector:
    app: s1
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poc
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /s1/*
        backend:
          service:
            name: s1
            port:
              number: 80
        pathType: Prefix
