apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc
  name: poc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: poc
    component: netcore-app
  type: LoadBalancer
