apiVersion: v1
kind: Service
metadata:
  name: s1
spec:
  selector:
    app: s1
  ports:
    - port: 8091
      protocol: TCP
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s2
spec:
  selector:
    app: s2
  ports:
    - port: 8092
      protocol: TCP
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s1api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: /s1/weather
spec:
  rules:
  - http:
      paths:
      - path: /s1/*
        backend:
          service:
            name: s1
            port:
              number: 8091
        pathType: Prefix

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s2api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-path: /s2/weather
spec:
  rules:
  - http:
      paths:
      - path: /s2/*
        backend:
          service:
            name: s2
            port:
              number: 8092
        pathType: Prefix
